sudo: required
language: generic
os: linux
dist: trusty
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
env:
  - NODE_LABELS="Linux Ubuntu Ubuntu-14.04"
script:
  - ./.jenkins
